version: '3.8'

services:
  backend:
    build: ./backend
    container_name: app_backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge